fedspendingtransparency/data-act-broker

README.md, dataactbroker/handlers/accountHandler.py, dataactbroker/handlers/fileHandler.py, tests/fileTests.py
Changed procurement to program_activity, and updated unit tests and documentation
=> Program activity name change

dataactbroker/handlers/aws/session.py, dataactbroker/scripts/setupEmails.py
Makes timeout longer and update's email template text.
=> Session timeout update

dataactbroker/scripts/initialize.py
Make this consistent with the code base currently in dev. I didn't put a huge amount of thought into this, since the e-mail template stuff is being reworked--this just ensures that the broker setup in its current form can run w/o errors.
=> update email setup function signature

dataactbroker/handlers/aws/session.py
Small fix to make sure all errors in the local dynamo table creation code are raised.
=> make sure all errors are raised when created local dynamo table

tests/runTests.py, tests/userTests.py
@nmonga91 Those last two commits never did show up on GitHub, even after a force push. Here they are as a separate branch. Can you take a look and merge tomorrow? Thanks!
=> Account expiration feature2

README.md
@jworcestBAH or @nmonga9: remove outdated config info and point users to consolidated config documentation
=> Db 247 doc cleanup

README.md
@bsweger, @nmonga91:  Small PR here to update the route documentation for submit_files and check_status so front-end devs can refer to the new usage in the dev documentation.
=> Updated route documentation for submit_files and check_status

dataactbroker/handlers/accountHandler.py
=> Hotfix: fixing broken email links

dataactbroker/handlers/fileHandler.py, dataactbroker/handlers/jobHandler.py, tests/fileTests.py
@bsweger, @nmonga91: This allows existing submissions to be updated, in which case new information overwrites the old submission, and any affected jobs have their status reset.
=> Db 319 update submission

requirements.txt
=> Fixing logstash ordering in requirements.txt

.gitignore, dataactbroker/handlers/aws/sesEmail.py, dataactbroker/scripts/setupEmails.py
@bsweger, @nmonga91: This PR improves handling of missing values in templates, and fixes the typo that caused the error with titles in the admin registration notification
=> Db 427 fix templating

dataactbroker/app.py, dataactbroker/handlers/aws/sesEmail.py
Code updates per comments on PR #38
Updating aws config items to only be used as needed:
Only set DynamoDB region when not running locally
Default to not using aws keys for ses connection
=> Hotfix aws config

dataactbroker/scripts/initialize.py, dataactbroker/scripts/setupEmails.py
Remove sudo check from the broker setup script.
@jworcestBAH or @kaitlin
=> Setup hotfix broker

dataactbroker/handlers/accountHandler.py
=> Preventing email token from being deleted to resolve registration email redirection issue.

dataactbroker/handlers/accountHandler.py, tests/userTests.py
@nmonga91 or @bsweger:  This prevents users from repeating the registration process.
=> Preventing duplicate registration and related unit test

dataactbroker/handlers/accountHandler.py, dataactbroker/handlers/fileHandler.py, dataactbroker/handlers/userHandler.py, dataactbroker/permissions.py, dataactbroker/scripts/setupEmails.py, tests/fileTests.py
Checking that user either owns submission or is an admin for checking status and updating existing submissions.
=> Db=381 submission permissions

dataactbroker/handlers/userHandler.py, dataactbroker/scripts/setupEmails.py
Late entry for the punchlist:
* update text for registration e-mail template
* update e-mail template setup script to ensure that it can be re-run to update existing data
=> Update email text

dataactbroker/permissions.py
Removed the extra check that was causing issues
=> Removed problematic session check for VPN

dataactbroker/fileRoutes.py, dataactbroker/handlers/fileHandler.py
Adding rss route to return signed URL, doing a PR to both dev and staging for this.
=> Added route to get RSS file

dataactbroker/handlers/fileHandler.py
When running locally RSS route will check the local folder for the file
=> Added handling for local to RSS route

README.md, dataactbroker/handlers/fileHandler.py
Small addition to error report route and docs for cross-file report
=> Db 252 cross file
